---
name: "Build and deploy docker image"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'main'
jobs:
  build:
    # when running on self-hosted, uncomment the following and comment out the subsequent line
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # when running on a self-hosted nixos system, I removed the following 2 uses...
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: imjasonh/setup-crane@v0.1
      - run: |
          set -eu

          OCI_ARCHIVE=$(nix build --no-link --print-out-paths .#docker)
          DOCKER_REPOSITORY="docker://ghcr.io/coral-protocol/coral-dbg"

          gzip --decompress --stdout --force < $OCI_ARCHIVE > result.tar
          crane push ./result.tar "ghcr.io/coral-protocol/coral-dbg"
        if: github.ref == 'refs/heads/main'
